export const Routes = {
    DashboardOverview: { path: "/dashboard" },
    Profile: { path: "/profile" },
    EditProfile: { path: "/editProfile" },
    BootstrapTables: { path: "/tables/user-tables" },
    CirclesPage: { path: "/circles" },
    WalletPage: { path: "/wallet" },
    PayoutsPage: { path: "/animated-video" },
    AnalyticsPage: { path: "/faq-management" },
    NotificationsPage: { path: "/notification" },
    DisputesWrapper: { path: "/disputes" },
    Help: { path: "/help",},
    FAQ: { path: "/faq",},
    Signin: { path: "/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/reset-password" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Tables: { path: "/components/tables" },
};
